# Generated by Django 2.2.1 on 2019-06-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
                ('bg_img', models.ImageField(blank=True, null=True, upload_to='content/media/Images/Experience/bg_imgs/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='content/media/Images/Experience/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('mid', 'Email-Identification-Required'), ('high', 'Admin-Permission-Required'), ('private', 'Private')], default='public', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='content/media/Site-Data/Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='content/media/Site-Data/Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('bg_img', models.ImageField(upload_to='content/media/Images/Interests/')),
                ('link', models.URLField(verbose_name='URL to the Interests Page')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('update', 'Update'), ('graffiti', 'Graffiti'), ('one_liner', 'One Liner'), ('dream', 'Dream'), ('political', 'Political'), ('plan', 'Plan'), ('goal', 'Goal'), ('super-optimistic-dream', 'Super Optimistic Dream'), ('story', 'Story'), ('real-story', 'Real Story'), ('bizarre_idea', 'Bizarre Idea'), ('other', 'Other')], default='update', max_length=200)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('mid', 'Email-Identification-Required'), ('high', 'Admin-Permission-Required'), ('private', 'Private')], max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='content/media/Personal_Blog/')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('position', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='contents/media/Projects/<django.db.models.fields.CharField>/')),
                ('ved', models.FileField(upload_to='contents/media/Projects/<django.db.models.fields.CharField>/')),
                ('other_stuff', models.FileField(upload_to='contents/media/Projects/<django.db.models.fields.CharField>/')),
                ('blog', models.URLField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_summary', models.TextField()),
                ('end_summary', models.TextField()),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Project')),
            ],
        ),
    ]
