# Generated by Django 2.2.1 on 2019-06-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.SmallIntegerField(verbose_name='Year')),
                ('summary', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='content/media/Images/Timeline_Images/')),
                ('link', models.URLField(verbose_name='stories page')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('mid', 'Email-Identification-Required'), ('high', 'Admin-Permission-Required'), ('private', 'Private')], default='public', max_length=100)),
            ],
        ),
    ]
