# Generated by Django 2.2.1 on 2019-06-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_timeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_detail',
            old_name='details',
            new_name='detail',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='stories page'),
        ),
    ]
