# Generated by Django 2.2.1 on 2019-06-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190609_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_blog_post',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
    ]
