# Generated by Django 2.2.1 on 2019-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190614_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_blog',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project_blog_post',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
