# Generated by Django 2.2.1 on 2019-07-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190614_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='content/media/Projects/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_stuff',
            field=models.FileField(upload_to='content/media/Projects/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ved',
            field=models.FileField(upload_to='content/media/Projects/<django.db.models.fields.CharField>/'),
        ),
    ]
