# Generated by Django 2.2.1 on 2019-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190701_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='blog',
        ),
        migrations.AddField(
            model_name='project',
            name='project_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_src',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_ved',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/media/Projects/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_stuff',
            field=models.FileField(blank=True, null=True, upload_to='content/media/Projects/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ved',
            field=models.FileField(blank=True, null=True, upload_to='content/media/Projects/<django.db.models.fields.CharField>/'),
        ),
    ]
