# Generated by Django 2.2.1 on 2019-07-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190707_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='bg_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
